[project]
name = "resume-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "neo4j>=5.28.1",
    "numpy>=2.2.4",
    "sentence-transformers>=4.0.2",
]
